# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

def shared_pods
  pod 'RealmSwift'
end

target 'Grades' do
  platform :ios, '11.0'
  # Pods for Grades
  shared_pods
  pod 'JTAppleCalendar'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftMessages'
end

target 'GradesTests' do
  shared_pods
end

#target 'GradesWatch Extension' do
#  platform :watchos, '5.3'
#  # Pods for GradesWatch Extension
#  shared_pods
#end
